name: Release

on:
  push:
    tags: [ "release/*" ]

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Get Release Version
      run:  echo "version=$(echo '${{github.ref_name}}' | cut -d '/' -f 2)" >> $GITHUB_ENV

    - name: Build Windows Amd64
      run: GOOS=windows GOARCH=amd64 .ci/release.sh ${{secrets.PocketAppId}} ${{env.version}} pocket-cli-win-amd64.exe

    - name: Build Windows x386
      run: GOOS=windows GOARCH=386 .ci/release.sh ${{secrets.PocketAppId}} ${{env.version}} pocket-cli-win-386.exe

    - name: Build Linux Amd64
      run: GOOS=linux GOARCH=amd64 .ci/release.sh ${{secrets.PocketAppId}} ${{env.version}} pocket-cli-linux-amd64

    - name: Build Linux x386
      run: GOOS=linux GOARCH=386 .ci/release.sh ${{secrets.PocketAppId}} ${{env.version}} pocket-cli-linux-386

    - name: Build Mac Amd64
      run: GOOS=darwin GOARCH=amd64 .ci/release.sh ${{secrets.PocketAppId}} ${{env.version}} pocket-cli-mac-amd64

    - name: Build Mac Apple Silicon (arm)
      run: GOOS=darwin GOARCH=arm64 .ci/release.sh ${{secrets.PocketAppId}} ${{env.version}} pocket-cli-mac-arm64

    - name: Get release text
      run: .ci/git-changelog.sh ${{env.version}} https://github.com/UnseenWizzard/pocket-cli

    - uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        artifacts: "pocket-cli*"
        name: "${{env.version}}"
        bodyFile: "CHANGELOG.md"